site_name: SUA Wiki
site_url: https://sua.ac/wiki/

theme:
  name: material
  theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh
  features:
    - navigation.indexes

plugins:
  - search:
      lang: ja
  - awesome-pages
  - charts:
      vega_theme_dark: default
  - i18n:
      default_language: zh
      languages:
        zh: 中文
        en: english
      nav_translations:
        en:
          2023 广东省大学生程序设计竞赛: The 2023 Guangdong Provincial Collegiate Programming Contest
          2022 ICPC 亚洲区域赛南京站: The 2022 ICPC Asia Nanjing Regional Contest
          2021 ICPC 亚洲区域赛澳门站: The 2021 ICPC Asia Macau Regional Contest
          2021 ICPC 亚洲区域赛南京站: The 2021 ICPC Asia Nanjing Regional Contest
          2021 四川省大学生程序设计竞赛: The 2021 Sichuan Provincial Collegiate Programming Contest
          2020 ICPC 亚洲区域赛南京站: The 2020 ICPC Asia Nanjing Regional Contest
          2019 陕西省大学生程序设计竞赛: The 2019 Shaanxi Provincial Collegiate Programming Contest
          2019 山东省大学生程序设计竞赛: The 2019 Shandong Provincial Collegiate Programming Contest
          2019 浙江省大学生程序设计竞赛: The 2019 Zhejiang Provincial Collegiate Programming Contest
          2019 浙江大学程序设计竞赛: The 2019 Zhejiang University Programming Contest
          2018 ICPC 亚洲区域赛青岛站: The 2018 ICPC Asia Qingdao Regional Contest
          2018 ICPC 亚洲区域赛青岛站网络赛: The 2018 ICPC Asia Qingdao Regional Contest, Online
          2018 浙江省大学生程序设计竞赛: The 2018 Zhejiang Provincial Collegiate Programming Contest
          2018 浙江大学程序设计竞赛: The 2018 Zhejiang University Programming Contest
          2017 中国大学生程序设计竞赛秦皇岛站: The 2017 China Collegiate Programming Contest Qinhuangdao Site
          2017 浙江省大学生程序设计竞赛: The 2017 Zhejiang Provincial Collegiate Programming Contest
          2017 浙江大学程序设计竞赛: The 2017 Zhejiang University Programming Contest

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details:
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

extra_css:
    - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra:
  alternate:
    - name: 中文
      link: /wiki/
      lang: zh
    - name: English
      link: /wiki/en/
      lang: en
